import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';

// SEO regression harness for apps/web.
//
// This config is intentionally minimal and isolated from `next.config.mjs`:
//   - `next.config.mjs` is consumed by `next build`/`next dev`/`next start`.
//   - This file is consumed only by Vitest.
// The two pipelines share no state, so changing one cannot break the other.
//
// We use happy-dom (lighter than jsdom) for rendering React Server Components
// output via `react-dom/server`.

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: [
      // Mirror the `@/` alias that `next.config.mjs`/`tsconfig.json` define so
      // test imports like `@/lib/shared` resolve correctly under Vitest.
      { find: '@', replacement: fileURLToPath(new URL('./src', import.meta.url)) },
      // `collections/server` is a virtual module generated by `fumadocs-mdx`
      // at build time (see `apps/web/source.config.ts`). It exports the
      // `docs` and `blog` collections derived from MDX content. Under Vitest
      // we stub it via a small in-repo fixture so we don't have to boot the
      // Fumadocs MDX generator. The fixture is intentionally tiny; the SEO
      // tests only need the collection shape (`.toFumadocsSource()` and
      // `.getPages()`).
      {
        find: /^collections\/server$/,
        replacement: fileURLToPath(new URL('./tests/seo/fixtures/collections.ts', import.meta.url)),
      },
      // `fumadocs-core/source` provides the `loader()` helper that turns a
      // Fumadocs collection into an enumerable page tree. We stub *both*
      // `fumadocs-core/source` and `fumadocs-core/source/lucide-icons` with
      // the same fixture, which exposes `loader`, `toFumadocsSource`, and
      // `lucideIconsPlugin`. Using exact-string aliases keeps Vite from
      // prefix-matching and accidentally rewriting sub-paths.
      {
        find: /^fumadocs-core\/source$/,
        replacement: fileURLToPath(new URL('./tests/seo/fixtures/loader.ts', import.meta.url)),
      },
      {
        find: /^fumadocs-core\/source\/lucide-icons$/,
        replacement: fileURLToPath(new URL('./tests/seo/fixtures/loader.ts', import.meta.url)),
      },
      // `fumadocs-mdx/runtime/server` exposes `toFumadocsSource(pages, metas)`
      // which iterates over raw page entries. Stub it the same way so
      // `src/lib/source.ts` can run end-to-end under Vitest.
      {
        find: 'fumadocs-mdx/runtime/server',
        replacement: fileURLToPath(new URL('./tests/seo/fixtures/loader.ts', import.meta.url)),
      },
      // `next/font/google` requires network access and a Next build pipeline;
      // stub it with a tiny module that returns a no-op class name so the
      // layout component can be imported without crashing.
      {
        find: 'next/font/google',
        replacement: fileURLToPath(
          new URL('./tests/seo/fixtures/next-font-google.ts', import.meta.url)
        ),
      },
      // The llms.txt route handlers live in directories whose name contains
      // a dot, which Vite's resolver misinterprets as a file extension.
      // Map the dotted paths to plain aliases that Vite handles natively.
      {
        find: '~llms-txt-route',
        replacement: fileURLToPath(new URL('./src/app/llms.txt/route.ts', import.meta.url)),
      },
      {
        find: '~llms-full-txt-route',
        replacement: fileURLToPath(new URL('./src/app/llms-full.txt/route.ts', import.meta.url)),
      },
    ],
  },
  // Stub modules that pull in Next-only APIs or external services at
  // import time.
  define: {
    'process.env.NEXT_PUBLIC_SITE_URL': JSON.stringify('https://errors.deessejs.com'),
    'process.env.NEXT_PUBLIC_APP_URL': JSON.stringify('https://errors.deessejs.com'),
  },
  test: {
    environment: 'happy-dom',
    include: ['tests/**/*.test.ts', 'tests/**/*.test.tsx'],
    // Snapshot files are co-located with the test files by default; this
    // explicit `resolveSnapshotPath` keeps them inside the `tests/` tree so
    // they are easy to review in PR diffs.
    resolveSnapshotPath: (testPath, snapExtension) => {
      const slashed = testPath.replace(/\\/g, '/');
      return slashed.replace(/\.test\.(ts|tsx)$/, `.snap${snapExtension}`);
    },
  },
});
