import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';

// SEO regression harness for apps/web.
//
// This config is intentionally minimal and isolated from `next.config.mjs`:
//   - `next.config.mjs` is consumed by `next build`/`next dev`/`next start`.
//   - This file is consumed only by Vitest.
// The two pipelines share no state, so changing one cannot break the other.
//
// We use happy-dom (lighter than jsdom) for rendering React Server Components
// output via `react-dom/server`.

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: [
      // Mirror the `@/` alias that `next.config.mjs`/`tsconfig.json` define so
      // test imports like `@/lib/shared` resolve correctly under Vitest.
      { find: '@', replacement: fileURLToPath(new URL('./src', import.meta.url)) },
      // `collections/server` is a virtual module generated by `fumadocs-mdx`
      // at build time (see `apps/web/source.config.ts`). It exports the
      // `docs` and `blog` collections derived from MDX content. We stub it
      // so we don't have to boot the Fumadocs MDX generator for SEO tests.
      {
        find: /^collections\/server$/,
        replacement: fileURLToPath(
          new URL('./tests/seo/fixtures/stubs/collections.ts', import.meta.url)
        ),
      },
      // Fumadocs runtime modules: `loader`, `toFumadocsSource`, and
      // `lucideIconsPlugin`. We stub all three with the same fixture so
      // `src/lib/source.ts` runs end-to-end under Vitest.
      {
        find: /^fumadocs-core\/source$/,
        replacement: fileURLToPath(
          new URL('./tests/seo/fixtures/stubs/fumadocs.ts', import.meta.url)
        ),
      },
      {
        find: /^fumadocs-core\/source\/lucide-icons$/,
        replacement: fileURLToPath(
          new URL('./tests/seo/fixtures/stubs/fumadocs.ts', import.meta.url)
        ),
      },
      {
        find: 'fumadocs-mdx/runtime/server',
        replacement: fileURLToPath(
          new URL('./tests/seo/fixtures/stubs/fumadocs.ts', import.meta.url)
        ),
      },
      // `next/font/google` requires network access and a Next build pipeline;
      // we stub it with a no-op class so the layout component can be
      // imported without crashing.
      {
        find: 'next/font/google',
        replacement: fileURLToPath(
          new URL('./tests/seo/fixtures/stubs/next-font-google.ts', import.meta.url)
        ),
      },
    ],
  },
  // Stub modules that pull in Next-only APIs or external services at
  // import time.
  define: {
    'process.env.NEXT_PUBLIC_SITE_URL': JSON.stringify('https://errors.deessejs.com'),
    'process.env.NEXT_PUBLIC_APP_URL': JSON.stringify('https://errors.deessejs.com'),
  },
  test: {
    environment: 'happy-dom',
    include: ['tests/**/*.test.ts', 'tests/**/*.test.tsx'],
  },
});
